name: push_files
on: push
jobs:
  onPushOfFiles:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install node modules
        run: npm ci
      - name: Run test
        run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install node modules
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "deploying"